[versions]
assertj = "3.26.3"
jackson = "2.18.1"
kotlin = "2.2.21"
kotlinCoroutines = "1.10.2"
compose = "1.9.3"

[libraries]
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm", version.ref = "kotlinCoroutines" }
jackson-module-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jackson" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj"}


[bundles]
aoc-implementation = [ "kotlinx-coroutines", "jackson-module-kotlin" ]
aoc-test = [ "assertj-core" ]

[plugins]
jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
compose = { id = "org.jetbrains.compose", version.ref = "compose"}
composeCompiler =  { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin"}
